### ISSUE TITLE
When access response body - NoSuchMethodError: io.circe.Json.cursor()

### ISSUE THREAD

**Issue by zartstrom** [agourlay/cornichon#108]
scala 2.12.1
circe version 0.7.0
finch version 0.12.0
cornichon 0.10.4

I have a finch service against which I run some tests.
This scenario works:
```
Scenario("check heartbeat") {
      When I get("/heartbeat")
      Then assert status.is(200)
```

But when I add a check (`assert body.path("host").isPresent`) on the response body (the endpoint is supposed to return a json like `{"message": "I'm up", "host": "172.23.14.202"}`)
```
Scenario("check heartbeat") {
      When I get("/heartbeat")
      Then assert status.is(200)
      And assert body.path("host").isPresent
    }
```
I get the following stacktrace:
```
Starting scenario 'check heartbeat'
Exception in thread "cornichon-1" java.lang.NoSuchMethodError: io.circe.Json.cursor()Lio/circe/Cursor;
	at com.github.agourlay.cornichon.json.JsonPath.cursor(JsonPath.scala:18)
	at com.github.agourlay.cornichon.json.JsonPath.run(JsonPath.scala:15)
	at com.github.agourlay.cornichon.json.JsonPath$.$anonfun$run$4(JsonPath.scala:64)
	at scala.util.Either.map(Either.scala:297)
	at com.github.agourlay.cornichon.json.JsonPath$.run(JsonPath.scala:64)
	at com.github.agourlay.cornichon.json.JsonSteps$.$anonfun$resolveRunJsonPath$1(JsonSteps.scala:288)
	at scala.util.Either.flatMap(Either.scala:284)
	at com.github.agourlay.cornichon.json.JsonSteps$.com$github$agourlay$cornichon$json$JsonSteps$$resolveRunJsonPath(JsonSteps.scala:288)
	at com.github.agourlay.cornichon.json.JsonSteps$JsonStepBuilder.$anonfun$isPresent$2(JsonSteps.scala:131)
	at com.github.agourlay.cornichon.steps.regular.assertStep.CustomMessageEqualityAssertion$.fromSession(EqualityAssertion.scala:53)
	at com.github.agourlay.cornichon.json.JsonSteps$JsonStepBuilder.$anonfun$isPresent$1(JsonSteps.scala:130)
	at com.github.agourlay.cornichon.steps.regular.assertStep.AssertStep.$anonfun$run$2(AssertStep.scala:23)
	at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:267)
	at com.github.agourlay.cornichon.steps.regular.assertStep.AssertStep.$anonfun$run$1(AssertStep.scala:23)
	at com.github.agourlay.cornichon.util.Timing$.withDuration(Timing.scala:10)
	at com.github.agourlay.cornichon.steps.regular.assertStep.AssertStep.run(AssertStep.scala:25)
	at com.github.agourlay.cornichon.core.Engine.$anonfun$runSteps$5(Engine.scala:47)
	at scala.util.Either.fold(Either.scala:125)
	at com.github.agourlay.cornichon.core.Engine.$anonfun$runSteps$1(Engine.scala:47)
	at scala.Option.map(Option.scala:146)
	at com.github.agourlay.cornichon.core.Engine.runSteps(Engine.scala:41)
	at com.github.agourlay.cornichon.core.Engine.$anonfun$runSteps$8(Engine.scala:51)
	at scala.util.Either.fold(Either.scala:125)
	at com.github.agourlay.cornichon.core.Engine.$anonfun$runSteps$6(Engine.scala:51)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Maybe it is a conflict in namespaces but I didn't figure it out yet.

**Comment by agourlay** [comment]
Do you have circe 0.7.0 in the cornichon classpath?
Cornichon is currently built with Circe 0.6.1
https://github.com/agourlay/cornichon/blob/master/build.sbt#L50

If it is the case, you just found out that those two releases are not binary compatible.

**Comment by zartstrom** [comment]
Thanks for your answer, it was helpful to me :+1: 
Before I tried to downgrade to circe 0.6.1 and encountered the same error. But I just found out that finch-circe brings the dependency to 0.7.0 with it anyway, and this circe dependency gets resolved first in my project.
Probably I'll create a separate project for the cornichon tests, that seems simplest/cleanest to me.

**Comment by agourlay** [comment]
Great, separating projects is always better in the long run 👍 

I will release a new version dependending on circe 0.7.0 as soon as the projects I am depending on get updated as well.
