### ISSUE TITLE
import inside a Scenario causes NPE

### ISSUE THREAD

**Issue by rjsvaljean** [agourlay/cornichon#141]
Test case:

```
class SomeCornichonFeature extends CornichonFeature {
  override def feature: FeatureDef = Feature("Some Feature") {
    Scenario("Some Scenario") {
      import scala.util.Try
      Try(1)
      Then assert status.is(200)
    }
  }
}
```

Compile error:

```
> test-only SomeCornichonFeature
[info] Compiling 1 Scala source to /Users/ratan/.../target/scala-2.12/test-classes...
[error] /Users/ratan/.../CornichonFeature.scala:7: exception during macro expansion:
[error] java.lang.NullPointerException
[error]         at com.github.agourlay.cornichon.macros.package$Macro.typecheck(package.scala:74)
[error]         at com.github.agourlay.cornichon.macros.package$Macro.$anonfun$blockExpressionList$1(package.scala:57)
[error]         at scala.collection.immutable.List.map(List.scala:283)
[error]         at com.github.agourlay.cornichon.macros.package$Macro.blockExpressionList(package.scala:57)
[error]         at com.github.agourlay.cornichon.macros.package$Macro.blockOrApplyExpressionList(package.scala:40)
[error]         at com.github.agourlay.cornichon.macros.package$Macro.collectImpl(package.scala:24)
[error]     Scenario("Some Scenario") {
[error]                               ^
[error] /Users/ratan/.../CornichonFeature.scala:8: Unused import
[error]       import scala.util.Try
[error]                         ^
[error] two errors found
```

**Comment by matsluni** [comment]
I hit the same error today.
