### ISSUE TITLE
When using Http4sClient on Cornichon 1.7.0 exception is thrown: "toMillis not allowed on infinite Durations"

### ISSUE THREAD

**Issue by karolzmuda** [agourlay/cornichon#228]
Cornichon 1.7.0

When using experimental Http4sClient by setting config:

```
useExperimentalHttp4sClient = true
```

following exception is thrown when running tests:

```
2019/04/02 18:11:31 DEBUG[text-global-788] org.http4s.client.PoolManager - Requesting connection: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=500 closed=false
2019/04/02 18:11:31 DEBUG[text-global-788] org.http4s.client.PoolManager - Active connection not found. Creating new one. curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=500 closed=false
2019/04/02 18:11:31 DEBUG[text-global-785] org.http4s.blaze.channel.nio2.ByteBufferHead - Starting up.
2019/04/02 18:11:31 DEBUG[text-global-785] org.http4s.blaze.channel.nio2.ByteBufferHead - Stage ByteBufferHead sending inbound command: Connected
2019/04/02 18:11:31 DEBUG[text-global-785] org.http4s.client.blaze.ReadBufferStage - Stage started up. Beginning read buffering
2019/04/02 18:11:31 DEBUG[text-global-785] org.http4s.client.blaze.ReadBufferStage - Stage ReadBufferStage sending inbound command: Connected
2019/04/02 18:11:31 DEBUG[text-global-785] org.http4s.client.blaze.Http1Connection - Starting up.
2019/04/02 18:11:31 DEBUG[text-global-790] org.http4s.blazecore.ResponseHeaderTimeoutStage - Starting up.
java.lang.IllegalArgumentException: toMillis not allowed on infinite Durations
	at scala.concurrent.duration.Duration$Infinite.fail(Duration.scala:213)
	at scala.concurrent.duration.Duration$Infinite.toMillis(Duration.scala:218)
	at org.http4s.blazecore.ResponseHeaderTimeoutStage.stageStartup(ResponseHeaderTimeoutStage.scala:55)
	at org.http4s.blazecore.ResponseHeaderTimeoutStage.init(ResponseHeaderTimeoutStage.scala:60)
	at org.http4s.client.blaze.BlazeClient$.$anonfun$makeClient$21(BlazeClient.scala:128)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
	at monix.eval.Task$.unsafeStartNow(Task.scala:4249)
	at monix.eval.internal.TaskCreate$.$anonfun$asyncF$1(TaskCreate.scala:150)
	at monix.eval.internal.TaskCreate$.$anonfun$asyncF$1$adapted(TaskCreate.scala:140)
	at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:58)
	at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:564)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:115)
	at monix.eval.Task$.unsafeStartNow(Task.scala:4249)
	at monix.eval.internal.TaskBracket$BaseStart$$anon$1.onSuccess(TaskBracket.scala:143)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:143)
	at monix.eval.Task$.unsafeStartNow(Task.scala:4249)
	at monix.eval.internal.TaskBracket$BaseStart.apply(TaskBracket.scala:131)
	at monix.eval.internal.TaskBracket$BaseStart.apply(TaskBracket.scala:121)
	at monix.eval.internal.TaskRestartCallback.run(TaskRestartCallback.scala:65)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:146)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:39)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:65)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.AsyncScheduler.execute(AsyncScheduler.scala:29)
	at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:56)
	at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:564)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:115)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:192)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The problem occurs only if logging level is set to `DEBUG`, because the problematic line from file `ResponseHeaderTimeoutStage.scala:55` is:

```
logger.debug(s"Starting response header timeout stage with timeout of ${timeout.toMillis} ms")
```

When setting log level to `INFO` everything works fine.

I think that reason for this is setting `Duration.Inf` when creating `BlazeClientBuilder` in `Http4sClient.scala`:

```
private val (httpClient, safeShutdown) =
    BlazeClientBuilder(executionContext = ec)
      .withoutSslContext
      .withMaxTotalConnections(300)
      .withMaxWaitQueueLimit(500)
      .withIdleTimeout(Duration.Inf)
      .withResponseHeaderTimeout(Duration.Inf)
      .withRequestTimeout(Duration.Inf)
      .allocated
      .runSyncUnsafe(10.seconds)
```

Is my guess correct? :)

**Comment by agourlay** [comment]
This is a great analysis 🏆 

Thanks a lot for taking the time to dig in the internals and save me the work.

Now we can think about a fix.

The original problem is that the http client is used by all features which have different timeout configuration, so I managed the timeout myself in cornichon and not via the http client itself.

As the the http client's timeout configuration is mandatory, I went with the hack `Duration.Inf`.
In practice I think I could use something high like `1.hour` to remove the issue you found.

WDYT?

**Comment by karolzmuda** [comment]
You're welcome :)

Maybe if we want this value to be Inifinite and allow cornichon to manage timeout then we should define biggest possible finite duration, for example `Long.MaxValue.days` ?

It would be a nasty bug if there would be some mad man who would try to test 2 hour timeout in cornichon and he would get timeout at Http4s level instead ;) I know that it is not likely but I don't see a downside of defining it as big as possible.

**Comment by agourlay** [comment]
I have followed your reasonning in https://github.com/agourlay/cornichon/commit/fe153f7738492b69f76785a7266b69ce1c195f48 👍 

How urgent is it for you to have a release?

**Comment by karolzmuda** [comment]
We've managed to apply workaround by setting log level to INFO which got our tests running correctly again, so it is not that urgent ;)

**Comment by agourlay** [comment]
In that case I will close the issue and perform a release in a couple of weeks.

This is so far the only real change since `0.17`.

**Comment by agourlay** [comment]
FYI `0.17.1` with the fixed was released https://github.com/agourlay/cornichon/releases/tag/v0.17.1

**Comment by karolzmuda** [comment]
Thank you, we will bump the version in our dependencies.
