### ISSUE TITLE
HttpService network call error reporting

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#34]
The error reporting of the HttpService is not proper.

When the underlying call times out an expection is thrown and bubble up in the Engine.

```
exception thrown 'java.util.concurrent.TimeoutException: Futures timed out after [4 seconds]
[info]   	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   	at scala.concurrent.Await$.result(package.scala:190)
[info]   	at com.github.agourlay.cornichon.http.HttpService$$anonfun$withoutPayload$1$$anonfun$apply$9$$anonfun$apply$10$$anonfun$apply$11$$anonfun$apply$12.apply(HttpService.scala:47)
[info]   	at com.github.agourlay.cornichon.http.HttpService$$anonfun$withoutPayload$1$$anonfun$apply$9$$anonfun$apply$10$$anonfun$apply$11$$anonfun$apply$12.apply(HttpService.scala:46)
[info]   	at cats.data.Xor.flatMap(Xor.scala:98)
```

Use proper ```HttpCornichonError``` instead with explicit error message.

**Comment by agourlay** [comment]
fixed by https://github.com/agourlay/cornichon/commit/9ea9046841879f2f796ef9191168c703814918f7
