### ISSUE TITLE
After an update from 0.20.0 to 0.20.1

### ISSUE THREAD

**Issue by yanns** [agourlay/cornichon#607]
After an update from 0.20.0 to 0.20.1, we have some sporadic issues like:

```
*** FAILED ***
HTTP POST request to https://<...>

encountered the following error:
java.net.SocketException: HTTP connection closed: https://<server name>
  at org.http4s.blaze.client.BlazeClient$$anonfun$1.applyOrElse(BlazeClient.scala:72)
  at org.http4s.blaze.client.BlazeClient$$anonfun$1.applyOrElse(BlazeClient.scala:71)
  at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:263)
  at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:106)
  at unsafeRunSync @ com.github.agourlay.cornichon.http.client.Http4sClient.<init>(Http4sClient.scala:67)
  at *> @ fs2.Stream.$anonfun$parEvalMapUnordered$2(Stream.scala:2111)
  at get @ fs2.Stream.watch$1(Stream.scala:549)
  at complete @ fs2.Stream.$anonfun$parEvalMapUnordered$2(Stream.scala:2122)
```

**Comment by yanns** [comment]
must be related to https://github.com/agourlay/cornichon/pull/597

**Comment by yanns** [comment]
It only happens when running quite a lot of tests.
A step with 400 tests never fails.
A step with 1700 tests fails -> about 10 tests are failing.

**Comment by yanns** [comment]
Same tests running on localhost do not fail.

**Comment by agourlay** [comment]
Thanks for reporting the issue 👍 

At first glance, I do not understand why the stacktrace mentions:
```
at unsafeRunSync @ com.github.agourlay.cornichon.http.client.Http4sClient.<init>(Http4sClient.scala:67)
```

This happen only once, as a single global client is shared between all features 🤔 

Otherwise looking at the `http4s` diff, this [PR](https://github.com/http4s/http4s/pull/5349) is the only one catching my eye. 
Are you enabling `followRedirect` in the cornichon config?

**Comment by yanns** [comment]
No we don't use `followRedirect`.

**Comment by agourlay** [comment]
Another idea to investigate.

Is it possible for you to exclude the `http4s` dependencies coming from `cornichon-test-framework` and set it to`0.23.5` in your build file to validate that the issue was introduced by the version `0.23.6`?

**Comment by yanns** [comment]
I can try, but it will take time as I have to "reserve" the staging environment for that.

**Comment by agourlay** [comment]
I just published `0.20.2-SNAPSHOT` which contains an update for `http4s` among other things. (https://github.com/agourlay/cornichon/compare/v0.20.1...master)

Maybe you can give it a try :crossed_fingers:

**Comment by agourlay** [comment]
FYI [0.20.2](https://github.com/agourlay/cornichon/releases/tag/v0.20.2) is out shipping with several `http4s` updates.

**Comment by yanns** [comment]
Still seeing this issue
```
java.net.SocketException: HTTP connection closed: <server>
  at org.http4s.blaze.client.Http1Connection$$anonfun$executeRequest$14.applyOrElse(Http1Connection.scala:252)
  at org.http4s.blaze.client.Http1Connection$$anonfun$executeRequest$14.applyOrElse(Http1Connection.scala:251)
  at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:288)
  at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:130)
  at unsafeRunSync @ com.github.agourlay.cornichon.http.client.Http4sClient.<init>(Http4sClient.scala:67)
  at delayBy @ com.github.agourlay.cornichon.http.client.Http4sClient.$anonfun$runRequest$2(Http4sClient.scala:117)
```

**Comment by agourlay** [comment]
Another lead, it looks like a keep-alive issue where the `keep-alive server` < `keep-alive client`.
This could cause the client to use stale connections, that is already closed by the server.

But I have not changed any keep-alive setting recently :thinking:

**Comment by agourlay** [comment]
I followed my intuiting regarding a possible keep-alive mismatch in https://github.com/agourlay/cornichon/commit/bed4c2f5aa77875fa2912f31f6779a862db31e6d

I have just released master under `0.20.3-SNAPSHOT` for you to try :crossed_fingers:

**Comment by yanns** [comment]
I run all tests once, and could not observe this issue anymore with `0.20.3-SNAPSHOT`. 💯

**Comment by agourlay** [comment]
Happy to hear that!
I will cut the `0.20.3` release next week :memo:

**Comment by agourlay** [comment]
fixed in https://github.com/agourlay/cornichon/releases/tag/v0.20.3
