### ISSUE TITLE
OOME errors on failed assertion with long session

### ISSUE THREAD

**Issue by yanns** [agourlay/cornichon#769]
when the session contains lots of data (as it's possible when doing lots of retries), and when an assertion fails, we observe some OOME:

```
Exception in thread "io-compute-4" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:53)
	at java.base/java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:277)
	at java.base/java.lang.AbstractStringBuilder.inflateIfNeededFor(AbstractStringBuilder.java:1733)
	at java.base/java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1749)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1224)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1216)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1300)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1166)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1164)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1179)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1179)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
	at com.github.agourlay.cornichon.core.Session$.$anonfun$showSession$1(Session.scala:131)
	at com.github.agourlay.cornichon.core.Session$.$anonfun$showSession$1$adapted(Session.scala:123)
	at com.github.agourlay.cornichon.core.Session$$$Lambda$858/0x000000080140d000.apply(Unknown Source)
	at cats.Show$.$anonfun$show$1(Show.scala:66)
	at cats.Show$$$Lambda$59/0x0000000801122e20.show(Unknown Source)
	at cats.Show$Ops.show(Show.scala:52)
	at cats.Show$Ops.show$(Show.scala:52)
	at cats.Show$ToShowOps$$anon$1.show(Show.scala:57)
	at com.github.agourlay.cornichon.core.KeyNotFoundInSession.baseErrorMessage$lzycompute(Session.scala:155)
	at com.github.agourlay.cornichon.core.KeyNotFoundInSession.baseErrorMessage(Session.scala:155)
	at com.github.agourlay.cornichon.core.CornichonError.renderedMessage(CornichonError.scala:17)
	at com.github.agourlay.cornichon.core.CornichonError.renderedMessage$(CornichonError.scala:15)
	at com.github.agourlay.cornichon.core.KeyNotFoundInSession.renderedMessage$lzycompute(Session.scala:147)
	at com.github.agourlay.cornichon.core.KeyNotFoundInSession.renderedMessage(Session.scala:147)
	at com.github.agourlay.cornichon.core.CornichonError.toException(CornichonError.scala:24)
	at com.github.agourlay.cornichon.core.CornichonError.toException$(CornichonError.scala:24)
```

**Comment by agourlay** [comment]
Thank you for opening this interesting issue :+1: 

Could you please share an estimation regarding the Session object triggering those errors:
- the max number of keys in the Session
- the max number of values per key
- the max size of a single value

On top of having lots of retry, you likely have very large payloads saved in the history of `last-response-body`

The possible solutions are (non exclusive):
1. decrease the memory consumption of session diagnostic messages (a few low hanging fruits there)
2. redesign the Session object for large history and/or large values
3. introduce a hard limit for the max size of the string rendering the session error
4. enable users to set a threshold for the key history
5. manually prune session in the scenario

**Comment by agourlay** [comment]
I took care of the first option with https://github.com/agourlay/cornichon/pull/770

It is not a long term solution but it will definitely make the GC happier.

**Comment by agourlay** [comment]
I don't think there is a way of doing this right now.

One idea is to modify the `EventuallyStep` to accept a new flag to instruct it to not merge the inner nested session in case of error.

I can give it a try later today :crossed_fingers: 

In the meantime the easiest workaround for you is to increase the `interval` to generate less data.

**Comment by agourlay** [comment]
Another thing about your snippet:

```scala  
def wait_for_project_initialization(projectKey: String) = Attach {
    Eventually(maxDuration = 120 seconds, interval = 100 millis) {
      When I get_project(projectKey = projectKey)
      Then assert status.is(200)
      And assert body.path("initialized").is(true)
      And I save_body_path("version" -> "project-version")
    }
  }
```

The `Attach` instruction is not necessary I believe, as it is made to wrap several steps and not a single wrapper step.

This should work:

```scala
  def wait_for_project_initialization(projectKey: String) =
    Eventually(maxDuration = 120 seconds, interval = 100 millis) {
      When I get_project(projectKey = projectKey)
      Then assert status.is(200)
      And assert body.path("initialized").is(true)
      And I save_body_path("version" -> "project-version")
    }
```

Each `Attach` is triggering a macro at compile time which can get expensive on large files.

I recommend you scan your code base for unnecessary `Attach` instructions, you might be able easily improve your compilation time.

**Comment by agourlay** [comment]
First take https://github.com/agourlay/cornichon/pull/778
