### ISSUE TITLE
Custom BodyInput definition are not supported

### ISSUE THREAD

**Issue by agourlay** [agourlay/cornichon#93]
When defining a custom instance of BodyInput, the parsing taking place in the HttpService explods at it expects only member from a closed set of types.

```scala
       exception thrown 'scala.MatchError: {"email":"","password":"password"} (of class play.api.libs.json.JsObject)
             at com.github.agourlay.cornichon.json.CornichonJson$class.parseJson(CornichonJson.scala:21)
             at com.github.agourlay.cornichon.json.CornichonJson$.parseJson(CornichonJson.scala:102)
             at com.github.agourlay.cornichon.http.HttpService$$anonfun$resolveRequestParts$3$$anonfun$apply$2.apply(HttpService.scala:37)
             at com.github.agourlay.cornichon.http.HttpService$$anonfun$resolveRequestParts$3$$anonfun$apply$2.apply(HttpService.scala:35)
             at scala.Option.map(Option.scala:146)
             at com.github.agourlay.cornichon.http.HttpService$$anonfun$resolveRequestParts$3.apply(HttpService.scala:35)
             at com.github.agourlay.cornichon.http.HttpService$$anonfun$resolveRequestParts$3.apply(HttpService.scala:28)
             at cats.data.Xor.flatMap(Xor.scala:112)
             at com.github.agourlay.cornichon.http.HttpService.resolveRequestParts(HttpService.scala:28)
             at com.github.agourlay.cornichon.http.HttpService.com$github$agourlay$cornichon$http$HttpService$$runRequest(HttpService.scala:48)
             at com.github.agourlay.cornichon.http.HttpService$$anonfun$requestEffect$1.apply(HttpService.scala:127)
             at com.github.agourlay.cornichon.http.HttpService$$anonfun$requestEffect$1.apply(HttpService.scala:127)
             at com.github.agourlay.cornichon.steps.regular.EffectStep$$anonfun$1$$anonfun$apply$1.apply(EffectStep.scala:16)
             at com.github.agourlay.cornichon.steps.regular.EffectStep$$anonfun$1$$anonfun$apply$1.apply(EffectStep.scala:16)
             at cats.data.XorFunctions$class.catchNonFatal(Xor.scala:345)
             at cats.data.Xor$.catchNonFatal(Xor.scala:191)
             at com.github.agourlay.cornichon.steps.regular.EffectStep$$anonfun$1.apply(EffectStep.scala:16)
             at com.github.agourlay.cornichon.steps.regular.EffectStep$$anonfun$1.apply(EffectStep.scala:17)
             at com.github.agourlay.cornichon.util.Timing$.withDuration(Timing.scala:9)
             at com.github.agourlay.cornichon.steps.regular.EffectStep.run(EffectStep.scala:15)
             at com.github.agourlay.cornichon.core.Engine.runSteps(Engine.scala:47)
             at steps.wrapped.WithDataStep.steps$wrapped$WithDataStep$$repeatSuccessSteps$1(WithDataStep.scala:27)
             at steps.wrapped.WithDataStep$$anonfun$2.apply(WithDataStep.scala:45)
             at steps.wrapped.WithDataStep$$anonfun$2.apply(WithDataStep.scala:41)
             at com.github.agourlay.cornichon.util.Timing$.withDuration(Timing.scala:9)
             at steps.wrapped.WithDataStep.run(WithDataStep.scala:41)
             at com.github.agourlay.cornichon.core.Engine.runSteps(Engine.scala:47)
             at com.github.agourlay.cornichon.core.Engine.runScenario(Engine.scala:20)
             at com.github.agourlay.cornichon.CornichonFeature$class.runScenario(CornichonFeature.scala:41)
             at LoginFeature.runScenario(GoogleFeature.scala:15)
             at com.github.agourlay.cornichon.core.ScalatestIntegration$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$3.apply(ScalatestIntegration.scala:49)
             at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
             at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
             at org.scalatest.Transformer.apply(Transformer.scala:22)
             at org.scalatest.Transformer.apply(Transformer.scala:20)
             at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
             at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
             at LoginFeature.withFixture(GoogleFeature.scala:15)
             at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
             at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
             at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
             at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
             at org.scalatest.WordSp
```

Found by @kylepotts - see https://gitter.im/agourlay/cornichon?at=57cee7eb896559723045cf62

**Comment by agourlay** [comment]
In the final solution ```BodyInput``` is gone as it was not flexible and a third typeclass Circe Encoder is now required to pass custom object as http body.
